// Generated by CoffeeScript 1.6.2
(function() {
  var displayData, loadData, loadTemplate, templates;

  templates = {};

  $(function() {
    Handlebars.registerHelper('Currency', function(value) {
      return accounting.formatMoney(value);
    });
    ($('#options-nav')).tab();
    loadTemplate('text');
    loadTemplate('departments');
    loadTemplate('employees');
    return ($('#options-nav a')).click(function(e) {
      var $target, option, type;

      e.preventDefault();
      $target = $(e.target);
      option = $target.data('option');
      type = $target.data('type');
      return loadData(option, type);
    });
  });

  loadTemplate = function(name) {
    var templateHtml;

    templateHtml = ($("#" + name + "-template")).html();
    return templates[name] = Handlebars.compile(templateHtml);
  };

  loadData = function(option, type) {
    var call, url;

    url = (function() {
      switch (option) {
        case 'employees':
          return 'data/employees.json';
        case 'departments':
          return 'data/departments.json';
        case 'text':
          return 'data/homers-odyssey.txt';
      }
    })();
    call = $.ajax(url, {
      dataType: type
    });
    return call.done(function(data) {
      return displayData(option, data);
    });
  };

  displayData = function(option, data) {
    var html;

    html = templates[option]({
      value: data
    });
    return ($('#information-panel')).html(html);
  };

}).call(this);
