// Generated by CoffeeScript 1.6.2
(function() {
  var album, models, views;

  models = appAlbum.models;

  views = appAlbum.views;

  album = new models.Album();

  $(function() {
    ($(document)).on('dataLoaded', function() {
      var raw, view;

      raw = appAlbum.data.album;
      album.set('title', raw.title);
      album.set('imageRootPath', raw.imageRootPath);
      album.set('images', new models.ImageCollection(raw.images.slice(0, 6)));
      view = new views.AlbumView({
        el: $('#album-container'),
        model: album
      });
      return view.render();
    });
    ($('#add-button')).click(function() {
      var data, img;

      data = appAlbum.data;
      if (data.additionalImages.length > 0) {
        img = data.additionalImages.shift();
        (album.get('images')).push(new models.Image(img));
        if (data.additionalImages.length === 0) {
          return ($('#add-button')).attr('disabled', true);
        }
      }
    });
    return ($.getJSON('data/images.json')).then(function(data) {
      appAlbum.data = {
        album: {
          title: data.title,
          imageRootPath: data.imageRootPath,
          images: data.images.slice(0, 6)
        },
        additionalImages: data.images.slice(6, 10)
      };
      return ($(document)).trigger('dataLoaded');
    });
  });

}).call(this);
