// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var departmentsTemplate, displayDepartments, displayError, templateHtml;

    templateHtml = ($('#departments-template')).html();
    departmentsTemplate = _.template(templateHtml);
    ($('#first-button')).click(function(e) {
      var method;

      method = 'ajax() the old way';
      return $.ajax('data/departments.json', {
        dataType: 'json',
        complete: function(res) {
          return displayDepartments(method, res.responseJSON);
        },
        error: function(res) {
          return displayError(method, res.statusCode, res.statusText);
        }
      });
    });
    ($('#second-button')).click(function(e) {
      var method, xhr;

      method = 'ajax() with deferred';
      xhr = $.ajax('data/departments.json', {
        dataType: 'json'
      });
      xhr.done(function(data) {
        return displayDepartments(method, data);
      });
      return xhr.fail(function(res) {
        return displayError(method, res.statusCode, res.statusText);
      });
    });
    ($('#third-button')).click(function(e) {
      var method, xhr;

      method = 'get()';
      xhr = $.get('data/departments.json', {
        dataType: 'json'
      });
      xhr.done(function(data) {
        return displayDepartments(method, data);
      });
      return xhr.fail(function(res) {
        return displayError(method, res.statusCode, res.statusText);
      });
    });
    ($('#fourth-button')).click(function(e) {
      var method, xhr;

      method = 'getJSON()';
      xhr = $.getJSON('data/departments.json');
      xhr.done(function(data) {
        return displayDepartments(method, data);
      });
      return xhr.fail(function(res) {
        return displayError(method, res.statusCode, res.statusText);
      });
    });
    displayDepartments = function(method, departments) {
      return ($('#output')).html(departmentsTemplate({
        method: method,
        departments: departments
      }));
    };
    return displayError = function(method, code, text) {
      return alert("" + method + " failed: " + code + " - " + text);
    };
  });

}).call(this);
