// Generated by CoffeeScript 1.6.2
(function() {
  var addNewButton, buttonCounter;

  $(function() {
    ($('#first-button')).click(function(e) {
      e.preventDefault();
      return addNewButton();
    });
    ($('ul#color-list a')).click(function(e) {
      var color;

      e.preventDefault();
      color = ($(e.target)).data('color');
      return alert("Thank you for selecting " + color + ".");
    });
    return ($(document)).on('click', 'button.new-button', function(e) {
      var buttonValue;

      e.preventDefault();
      buttonValue = ($(e.target)).data('counter');
      return alert("You clicked button #" + buttonValue);
    });
  });

  buttonCounter = 1;

  addNewButton = function() {
    var html;

    html = $("<p><button class='btn btn-default new-button'    data-counter='" + buttonCounter + "'>    New Button " + buttonCounter + "    </button></p>");
    ($('#action-items')).append(html);
    return buttonCounter += 1;
  };

}).call(this);
