// Generated by CoffeeScript 1.6.2
(function() {
  ($(document)).ready(function() {
    return console.log('Document ready...');
  });

  $(function() {
    return console.log('Document ready (shortcut)...');
  });

}).call(this);
