// Generated by CoffeeScript 1.6.2
(function() {
  var sliderChange;

  $(function() {
    ($('#progressbar')).progressbar({
      value: 50
    });
    ($('#slider')).slider({
      value: 50,
      change: sliderChange
    });
    ($('#datepicker')).datepicker();
    return ($.getJSON('data/departments.json')).done(function(data) {
      return ($('#autocomplete')).autocomplete({
        source: data
      });
    }).fail(function(res) {
      return alert('Cannot load departments. ' + res.statusText);
    });
  });

  sliderChange = function(e, ui) {
    return ($('#progressbar')).progressbar('option', 'value', ui.value);
  };

}).call(this);
