// Generated by CoffeeScript 1.6.2
(function() {
  var addTodoItem;

  $(function() {
    var description, _i, _len, _ref, _results;

    ($('#add-button')).click(function(e) {
      var description;

      description = ($('#todo-description')).val();
      return addTodoItem(description);
    });
    ($('#todo-list')).on('click', '.delete-button', function(e) {
      if (confirm('Delete this item?')) {
        return ($(e.target)).parent('li').remove();
      }
    });
    ($('#todo-list')).on('click', '.complete-checkbox', function(e) {
      return ($(e.target)).parent('label').toggleClass('completed');
    });
    _ref = ['Pick up milk', 'Take the car in for an oil change', "Pick up tickets for Jenn's show"];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      description = _ref[_i];
      _results.push(addTodoItem(description));
    }
    return _results;
  });

  addTodoItem = function(description) {
    var itemHtml;

    itemHtml = "<li class='list-group-item'>      <label>      <input type='checkbox' class='complete-checkbox'>      " + description + "      </label>      <button class='delete-button btn btn-danger btn-xs'>Delete</button>    </li>";
    return ($('#todo-list')).append(itemHtml);
  };

}).call(this);
