// Generated by CoffeeScript 1.6.2
(function() {
  var addTodoItem, itemTemplate;

  itemTemplate = null;

  $(function() {
    var description, todos, _i, _len, _results;

    itemTemplate = _.template(($('#item-template')).html());
    ($('#add-button')).click(function(e) {
      var description;

      description = ($('#todo-description')).val();
      return addTodoItem(description);
    });
    ($('#todo-list')).on('click', '.delete-button', function(e) {
      if (confirm('Delete this item?')) {
        return ($(e.target)).parent('li').remove();
      }
    });
    ($('#todo-list')).on('click', '.complete-checkbox', function(e) {
      return ($(e.target)).parent('label').toggleClass('completed');
    });
    todos = ['Pick up milk', 'Take the car in for an oil change', 'Pick up tickets for Jenn\'s show'];
    _results = [];
    for (_i = 0, _len = todos.length; _i < _len; _i++) {
      description = todos[_i];
      _results.push(addTodoItem(description));
    }
    return _results;
  });

  addTodoItem = function(description) {
    return ($('#todo-list')).append(itemTemplate({
      description: description
    }));
  };

}).call(this);
