// Generated by CoffeeScript 1.6.2
(function() {
  var album, models;

  models = appAlbum.models;

  album = new models.Album();

  $(function() {
    return ($.getJSON('data/images.json')).then(function(data) {
      album.set('title', data.title);
      album.set('imageRootPath', data.imageRootPath);
      album.set('images', new models.ImageCollection(data.images));
      return appAlbum.displayAlbum(album.toJSON());
    });
  });

  appAlbum.data = {
    album: album
  };

}).call(this);
