// Generated by CoffeeScript 1.6.2
(function() {
  var Employee, EmployeeList, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Employee = (function(_super) {
    __extends(Employee, _super);

    function Employee() {
      _ref = Employee.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Employee.prototype.defaults = {
      id: 0,
      firstName: '',
      lastName: '',
      salesYtd: 0.0000
    };

    Employee.prototype.fullName = function() {
      return "" + (this.get('firstName')) + " " + (this.get('lastName'));
    };

    Employee.prototype.validate = function() {
      if ((this.get('firstName')).length === 0) {
        return 'First name is required';
      }
      if ((this.get('lastName')).length === 0) {
        return 'Last name is required';
      }
    };

    return Employee;

  })(Backbone.Model);

  EmployeeList = (function(_super) {
    __extends(EmployeeList, _super);

    function EmployeeList() {
      _ref1 = EmployeeList.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    EmployeeList.prototype.model = Employee;

    return EmployeeList;

  })(Backbone.Collection);

  window.app.models.Employee = Employee;

  window.app.collections.EmployeeList = EmployeeList;

}).call(this);
