// Generated by CoffeeScript 1.6.2
(function() {
  var Employee;

  window.demo = window.demo || {};

  Employee = (function() {
    function Employee(emp) {
      this.id = emp.id;
      this.firstName = emp.firstName;
      this.lastName = emp.lastName;
      this.salesYtd = emp.salesYtd;
    }

    Employee.prototype.fullName = function() {
      return "" + this.firstName + " " + this.lastName;
    };

    return Employee;

  })();

  window.demo.models = {
    Employee: Employee
  };

}).call(this);
